# Generated by Django 4.2.5 on 2023-10-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school_id',
            field=models.IntegerField(default=1),
        ),
    ]
