# Generated by Django 4.2.5 on 2023-10-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_logs_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logs',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
