# Generated by Django 4.2.5 on 2023-11-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='school_id',
            new_name='schoolid',
        ),
    ]
