# Generated by Django 4.2.5 on 2023-11-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(),
        ),
    ]
