# Generated by Django 4.2.5 on 2023-11-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='health_info_id',
        ),
        migrations.AddField(
            model_name='logs',
            name='health',
            field=models.CharField(default='110111000', max_length=100),
        ),
        migrations.AddField(
            model_name='logs',
            name='temperature',
            field=models.CharField(default='36.8', max_length=100),
        ),
    ]
