# Generated by Django 4.2.5 on 2023-11-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_remove_logs_health_info_id_logs_health_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='health',
        ),
        migrations.AddField(
            model_name='logs',
            name='q1',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='logs',
            name='q2',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='logs',
            name='q3',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='logs',
            name='q4',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='logs',
            name='q5',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='logs',
            name='q6',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='logs',
            name='q7',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='logs',
            name='q8',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='logs',
            name='q9',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
