# Generated by Django 4.2.5 on 2023-12-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_user_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mission',
            field=models.CharField(default='vv', max_length=800),
        ),
        migrations.AddField(
            model_name='profile',
            name='vission',
            field=models.CharField(default='vv', max_length=800),
        ),
    ]
